import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function downloadPDFReport(plots, summary) {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = 210;
  const pageH = 297;
  const margin = 12;
  const usableW = pageW - margin * 2;

  // ── Cover Page ──────────────────────────────────────────────
  pdf.setFillColor(15, 15, 15);
  pdf.rect(0, 0, pageW, pageH, "F");

  // Purple accent bar
  pdf.setFillColor(124, 58, 237);
  pdf.rect(0, 0, pageW, 3, "F");

  // Title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(28);
  pdf.setFont("helvetica", "bold");
  pdf.text("VisualBook", margin, 40);

  pdf.setFontSize(14);
  pdf.setTextColor(167, 139, 250);
  pdf.setFont("helvetica", "normal");
  pdf.text("CSV Analytics Report", margin, 52);

  // Divider
  pdf.setDrawColor(124, 58, 237);
  pdf.setLineWidth(0.5);
  pdf.line(margin, 58, pageW - margin, 58);

  // File info
  pdf.setFontSize(11);
  pdf.setTextColor(203, 213, 225);
  pdf.text(`File: ${summary.filename}`, margin, 72);
  pdf.text(`Rows: ${summary.rows?.toLocaleString()}`, margin, 82);
  pdf.text(`Columns: ${summary.columns}`, margin, 92);
  pdf.text(`Numeric Columns: ${summary.numeric_count}`, margin, 102);
  pdf.text(`Categorical Columns: ${summary.categorical_count}`, margin, 112);
  pdf.text(`Missing Values: ${summary.total_missing_pct}%`, margin, 122);
  pdf.text(`Charts Generated: ${plots.length}`, margin, 132);
  pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, 142);

  // Chart list on cover
  pdf.setFontSize(10);
  pdf.setTextColor(124, 58, 237);
  pdf.text("CHARTS IN THIS REPORT", margin, 162);
  pdf.setTextColor(148, 163, 184);
  plots.forEach((p, i) => {
    const col = i < 20 ? margin : pageW / 2;
    const row = 170 + (i % 20) * 6;
    if (i < 40) pdf.text(`${i + 1}. ${p.title}`, col, row);
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(71, 85, 105);
  pdf.text("Generated by VisualBook · visualbook.app", margin, pageH - 8);

  // ── Chart Pages ─────────────────────────────────────────────
  const chartsPerPage = 2;

  for (let i = 0; i < plots.length; i += chartsPerPage) {
    pdf.addPage();

    // Dark background
    pdf.setFillColor(15, 15, 15);
    pdf.rect(0, 0, pageW, pageH, "F");

    // Page header
    pdf.setFillColor(26, 26, 26);
    pdf.rect(0, 0, pageW, 14, "F");
    pdf.setFontSize(8);
    pdf.setTextColor(124, 58, 237);
    pdf.text("VISUALBOOK REPORT", margin, 9);
    pdf.setTextColor(71, 85, 105);
    pdf.text(
      `Page ${Math.floor(i / chartsPerPage) + 2} · ${summary.filename}`,
      pageW - margin,
      9,
      { align: "right" }
    );

    const pageCharts = plots.slice(i, i + chartsPerPage);

    for (let j = 0; j < pageCharts.length; j++) {
      const plot = pageCharts[j];
      const yStart = 20 + j * 130;

      // Chart card background
      pdf.setFillColor(26, 26, 26);
      pdf.roundedRect(margin, yStart, usableW, 125, 3, 3, "F");

      // Chart title
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(255, 255, 255);
      pdf.text(plot.title, margin + 4, yStart + 8);

      // Chart type badge
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(167, 139, 250);
      pdf.text(plot.plot_type.toUpperCase().replace(/_/g, " "), margin + 4, yStart + 15);

      // Description
      pdf.setFontSize(8);
      pdf.setTextColor(100, 116, 139);
      const descLines = pdf.splitTextToSize(plot.description, usableW - 8);
      pdf.text(descLines.slice(0, 2), margin + 4, yStart + 22);

      // Capture chart image
      const wrap = document.getElementById(`plotwrap-${plot.plot_id}`);
      const svgEl = wrap?.querySelector("svg.main-svg");

      if (svgEl) {
        try {
          const canvas = document.createElement("canvas");
          canvas.width  = svgEl.clientWidth  * 2;
          canvas.height = svgEl.clientHeight * 2;
          const ctx = canvas.getContext("2d");
          ctx.fillStyle = "#1a1a1a";
          ctx.fillRect(0, 0, canvas.width, canvas.height);

          const svgData = new XMLSerializer().serializeToString(svgEl);
          const url = URL.createObjectURL(
            new Blob([svgData], { type: "image/svg+xml" })
          );

          await new Promise((resolve) => {
            const img = new Image();
            img.onload = () => {
              ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
              URL.revokeObjectURL(url);

              const imgData = canvas.toDataURL("image/png");
              const imgH = 88;
              const imgY = yStart + 30;
              pdf.addImage(imgData, "PNG", margin + 2, imgY, usableW - 4, imgH);
              resolve();
            };
            img.onerror = resolve;
            img.src = url;
          });
        } catch (e) {
          pdf.setTextColor(100, 116, 139);
          pdf.setFontSize(9);
          pdf.text("Chart render unavailable", margin + 4, yStart + 70);
        }
      }
    }

    // Page footer
    pdf.setFontSize(7);
    pdf.setTextColor(51, 65, 85);
    pdf.text(
      `Page ${Math.floor(i / chartsPerPage) + 2} of ${Math.ceil(plots.length / chartsPerPage) + 1}`,
      pageW / 2,
      pageH - 5,
      { align: "center" }
    );
  }

  // ── Save ────────────────────────────────────────────────────
  const safeName = summary.filename.replace(".csv", "");
  pdf.save(`VisualBook_Report_${safeName}.pdf`);
}